---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: demo
spec:
  type: GitHub
  pathname: https://github.com/funkytaco/demo-subscription-gitops.git
  #secretRef:
  #  name: my-github-secret