---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: datacenter01
  namespace: baremetal-assets
spec:
  type: GitHub
  pathname: https://github.com/open-cluster-management/demo-subscription-gitops.git
  #secretRef:
  #  name: my-github-secret